---
output: 
  beamer_presentation:
    slide_level: 2
    template: theme/template.tex
    latex_engine: lualatex
    keep_tex: true
    
# set theme
eco-bielefeld: true
unibi-font: true
emoji: true
fontsize: 10pt
handout: false
aspectratio: 169

# set title, presenter, institute, date
title: "Title"
subtitle: "Subtitle"
author: "Presenter"
author-short: "Presenter"
institute: "Institute"
date: "`r Sys.Date()`"

# define table of contents
toc: true
toc-depth: 1
toc-title: "Outline" 

# define last slide
last-slide: true
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  out.height = "70%",
  fig.path   = "figures/"
) 
```

# Section 1

## LaTeX Engine

- This template uses the [Lelo font](https://camelot-typefaces.com/lelo).
- The font is set via `\usepackage{fontspec}`, which requires XeLaTeX or LuaLaTeX.
- 
- When compiling this template, make sure that either XeLaTeX or LuaLaTeX is the selected LaTeX engine.

## Subsection 1.2

- Eat eggs
- Drink coffee

# Section 2

## Subsection 2.1

- Eat spaghetti
- Drink wine

---

```{r, cars, fig.cap = "A scatterplot.", echo = FALSE}
plot(cars)
```

## Subsection 2.2

- Get in bed
- Count sheep
