name: render

on: push

jobs:
  render:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
    
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Render slides
        run: |
          install.packages("tinytex")
          tinytex::install_tinytex()
          install.packages("rmarkdown")
          rmarkdown::render("slides.Rmd")
        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.email "oelschlaeger.lennart@gmail.com"
          git config --local user.name "Lennart Oelschlaeger"
          git add .
          git commit -m 'Update CV :pencil:' || echo "No changes to commit"
          git push origin || echo "No changes to commit"